# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Xun Zhong
tagline:          'An Upcoming Programmer'
description:      'An upcoming <a>software engineer</a>'
url:              http://hyde.getpoole.com
baseurl:          /hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
